#!/bin/sh
EC2_INSTANCE_ID=`curl -m5 -s http://169.254.169.254/latest/meta-data/instance-id`
EC2_AVAILABILITY_ZONE=`curl -m5 -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
EC2_REGION=`echo $EC2_AVAILABILITY_ZONE | sed -e 's/-\([0-9]\+\)[a-z]\?/-\1/'`

if [ "$1" = "--export" ]; then
  export EC2_INSTANCE_ID EC2_AVAILABILITY_ZONE EC2_REGION
else
  cat <<EOF
EC2_INSTANCE_ID=$EC2_INSTANCE_ID
EC2_AVAILABILITY_ZONE=$EC2_AVAILABILITY_ZONE
EC2_REGION=$EC2_REGION
EOF
fi
